version: '3'

services:
  app:
    restart: always
    image: express-clm-demo:latest
    build: .
    env_file: .env
    environment:
      HOST: 0.0.0.0
    ports:
      - "3111:3000"
    container_name: code-level-metrics-qa
